version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - mongo-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - mongo-network
    environment:
      - ME_CONFIG_MONGODB_AUTH_DATABASE=mongopass
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=password

networks:
  mongo-network:
    external:
      name: 17ce5911a10d